HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Wed, 14 Dec 2016 22:17:32 GMT
Expires: Wed, 14 Dec 2016 22:22:32 GMT
Cache-Control: public, max-age=300
Vary: Accept-Language
Content-Encoding: gzip
Server: pablo
Content-Length: 1014
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Alt-Svc: quic=":443"; ma=2592000; v="35,34"
Connection: Keep-alive

{
"html_attributions" : [],
"result" : {
"address_components" : [
{
"long_name" : "525",
"short_name" : "525",
"types" : [ "street_number" ]
},
{
"long_name" : "South Wabash Avenue",
"short_name" : "S Wabash Ave",
"types" : [ "route" ]
},
{
"long_name" : "Chicago Loop",
"short_name" : "Chicago Loop",
"types" : [ "neighborhood", "political" ]
},
{
"long_name" : "Chicago",
"short_name" : "Chicago",
"types" : [ "locality", "political" ]
},
{
"long_name" : "Cook County",
"short_name" : "Cook County",
"types" : [ "administrative_area_level_2", "political" ]
},
{
"long_name" : "Illinois",
"short_name" : "IL",
"types" : [ "administrative_area_level_1", "political" ]
},
{
"long_name" : "United States",
"short_name" : "US",
"types" : [ "country", "political" ]
},
{
"long_name" : "60605",
"short_name" : "60605",
"types" : [ "postal_code" ]
},
{
"long_name" : "1603",
"short_name" : "1603",
"types" : [ "postal_code_suffix" ]
}
],
"adr_address" : "\u003cspan class=\"street-address\"\u003e525 S Wabash Ave\u003c/span\u003e, \u003cspan class=\"locality\"\u003eChicago\u003c/span\u003e, \u003cspan class=\"region\"\u003eIL\u003c/span\u003e \u003cspan class=\"postal-code\"\u003e60605-1603\u003c/span\u003e, \u003cspan class=\"country-name\"\u003eUSA\u003c/span\u003e",
"formatted_address" : "525 S Wabash Ave, Chicago, IL 60605, USA",
"geometry" : {
"location" : {
"lat" : 41.87506510000001,
"lng" : -87.62551649999999
},
"viewport" : {
"northeast" : {
"lat" : 41.87506845000001,
"lng" : -87.62527409999998
},
"southwest" : {
"lat" : 41.87505505,
"lng" : -87.6262437
}
}
},
"icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
"id" : "d04f2dc6c589ba4d6db742ae566858c6464b5971",
"name" : "525 S Wabash Ave",
"place_id" : "ChIJ65XAaKIsDogRfgnkNk2MDN4",
"reference" : "CmRbAAAASTd4OhADHQJrDsqYkf7DI9HkeCslYAfz3peuVK_0z2O8M2XZ9lwyRIT8kfR8Y2_zts7QDN9lyeTmYF8NN8-KSrKEYxAcd8n41Agcqr3DKgowTIO1v-w1I_Get9vLSe37EhCP4iEa_NnRDElgnp36qD44GhSvmSlhm7pl2NMkRws0d13BDxb__A",
"scope" : "GOOGLE",
"types" : [ "street_address" ],
"url" : "https://maps.google.com/?q=525+S+Wabash+Ave,+Chicago,+IL+60605,+USA&ftid=0x880e2ca268c095eb:0xde0c8c4d36e4097e",
"utc_offset" : -360,
"vicinity" : "Chicago"
},
"status" : "OK"
}
