HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Wed, 14 Dec 2016 22:17:16 GMT
Expires: Wed, 14 Dec 2016 22:22:16 GMT
Cache-Control: public, max-age=300
Vary: Accept-Language
Content-Encoding: gzip
Server: pablo
Content-Length: 1013
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Alt-Svc: quic=":443"; ma=2592000; v="35,34"
Connection: Keep-alive

{
"html_attributions" : [],
"result" : {
"address_components" : [
{
"long_name" : "328",
"short_name" : "328",
"types" : [ "street_number" ]
},
{
"long_name" : "South Wabash Avenue",
"short_name" : "S Wabash Ave",
"types" : [ "route" ]
},
{
"long_name" : "Chicago Loop",
"short_name" : "Chicago Loop",
"types" : [ "neighborhood", "political" ]
},
{
"long_name" : "Chicago",
"short_name" : "Chicago",
"types" : [ "locality", "political" ]
},
{
"long_name" : "Cook County",
"short_name" : "Cook County",
"types" : [ "administrative_area_level_2", "political" ]
},
{
"long_name" : "Illinois",
"short_name" : "IL",
"types" : [ "administrative_area_level_1", "political" ]
},
{
"long_name" : "United States",
"short_name" : "US",
"types" : [ "country", "political" ]
},
{
"long_name" : "60604",
"short_name" : "60604",
"types" : [ "postal_code" ]
},
{
"long_name" : "3902",
"short_name" : "3902",
"types" : [ "postal_code_suffix" ]
}
],
"adr_address" : "\u003cspan class=\"street-address\"\u003e328 S Wabash Ave\u003c/span\u003e, \u003cspan class=\"locality\"\u003eChicago\u003c/span\u003e, \u003cspan class=\"region\"\u003eIL\u003c/span\u003e \u003cspan class=\"postal-code\"\u003e60604-3902\u003c/span\u003e, \u003cspan class=\"country-name\"\u003eUSA\u003c/span\u003e",
"formatted_address" : "328 S Wabash Ave, Chicago, IL 60604, USA",
"geometry" : {
"location" : {
"lat" : 41.8774525,
"lng" : -87.62628549999999
},
"viewport" : {
"northeast" : {
"lat" : 41.87755375,
"lng" : -87.62595460000001
},
"southwest" : {
"lat" : 41.87741875,
"lng" : -87.6263958
}
}
},
"icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
"id" : "6fa36e1d92f51ab708338b4d72c35468721be260",
"name" : "328 S Wabash Ave",
"place_id" : "ChIJDyxh-6IsDogRqI0OqJc_km4",
"reference" : "CmRbAAAArZMwl76AMVWYDYpVddWztRj_rN-zwsOSZ0Shu96PfUPuicy25vJRhnRmvu624M7QESThSCgcx4FSNeVclrDU6j5OYBK8ll8qtSu5Ww8nUYWNA6f6JYAB3MUPWbVRd41fEhDJlNveFBpQ0cRSkyu_bH6YGhRoC7LxDgfPcDbekD32lSbVmbXlYA",
"scope" : "GOOGLE",
"types" : [ "street_address" ],
"url" : "https://maps.google.com/?q=328+S+Wabash+Ave,+Chicago,+IL+60604,+USA&ftid=0x880e2ca2fb612c0f:0x6e923f97a80e8da8",
"utc_offset" : -360,
"vicinity" : "Chicago"
},
"status" : "OK"
}
