HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Thu, 15 Dec 2016 16:21:49 GMT
Expires: Thu, 15 Dec 2016 16:21:49 GMT
Cache-Control: private, max-age=300
Vary: Accept-Language
Content-Encoding: gzip
Server: pablo
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Alt-Svc: quic=":443"; ma=2592000; v="35,34"
Transfer-Encoding: chunked
Connection: Keep-alive

{
"predictions" : [
{
"description" : "SpotHero, West Huron Street, Chicago, IL, United States",
"id" : "366fca1a92b10aab143ea5cd3e408594c8f2439d",
"matched_substrings" : [
{
"length" : 8,
"offset" : 0
}
],
"place_id" : "ChIJEyn6463TD4gR9Ta3uIauNyo",
"reference" : "ClRFAAAAiZV5rZ8TzpUBsEQhDnyalesMDE5fQBQ50bhP-LufREIDdyYzQaKQuREiLKU_jIbiLnPI7ZEF4j76kYFh3_LU2Fbpiqw_PSP8Y4-L8yHwsk0SEMTEZ8B3QSWeRPJK46xiHe4aFLfJxlxCrGIbhm0qZ3azn-tX5-Nr",
"structured_formatting" : {
"main_text" : "SpotHero",
"main_text_matched_substrings" : [
{
"length" : 8,
"offset" : 0
}
],
"secondary_text" : "West Huron Street, Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "SpotHero"
},
{
"offset" : 10,
"value" : "West Huron Street"
},
{
"offset" : 29,
"value" : "Chicago"
},
{
"offset" : 38,
"value" : "IL"
},
{
"offset" : 42,
"value" : "United States"
}
],
"types" : [ "establishment" ]
},
{
"description" : "Spot Hero Parking, North Seminary Avenue, Chicago, IL, United States",
"id" : "d06f45309050c38f5296b91c47764f6081772c86",
"matched_substrings" : [
{
"length" : 17,
"offset" : 0
}
],
"place_id" : "ChIJ7Zz4rAHTD4gRDm1r9sbQk0E",
"reference" : "CmRSAAAA_9AFGIBpPDalE-jL7sSnUdwomdbvsg2k8mCPO6qdH0nir8P_RFGCG-Fe-xdZcIhFmdwuQQUJA14MrwytqU-p-0tZnPZcOMM6SQj9BySBRoj6ytrY8Mf2HlrDuR42fjf-EhCOJvvifeYIIVr1CwYXGj1WGhQBNL3dWWzXK-ODSMvajfwlPxwItw",
"structured_formatting" : {
"main_text" : "Spot Hero Parking",
"main_text_matched_substrings" : [
{
"length" : 17,
"offset" : 0
}
],
"secondary_text" : "North Seminary Avenue, Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "Spot Hero Parking"
},
{
"offset" : 19,
"value" : "North Seminary Avenue"
},
{
"offset" : 42,
"value" : "Chicago"
},
{
"offset" : 51,
"value" : "IL"
},
{
"offset" : 55,
"value" : "United States"
}
],
"types" : [ "establishment" ]
},
{
"description" : "SpotHero, North Larrabee Street, Chicago, IL, United States",
"id" : "15e1a72c10cb4715bf46da4ef57bce2b9da53386",
"matched_substrings" : [
{
"length" : 8,
"offset" : 0
}
],
"place_id" : "ChIJwSzF9zvTD4gR32ykhRDvHGA",
"reference" : "ClRJAAAA5ZzQDyoJV7zkI0FTU5lSI9gwoh3G-Ki5E_q4wrwVV_vK6NnVi34DcVsVsI1V1RvyKi3izp1N-n9t9X_WsHvkkyyu5FtmnpvIW9SdEQ2UMhsSEIjd8BiyInbSp7iEUZ6_BcUaFFgPXW4NXqwEp7FFKmPENxKAFCoc",
"structured_formatting" : {
"main_text" : "SpotHero",
"main_text_matched_substrings" : [
{
"length" : 8,
"offset" : 0
}
],
"secondary_text" : "North Larrabee Street, Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "SpotHero"
},
{
"offset" : 10,
"value" : "North Larrabee Street"
},
{
"offset" : 33,
"value" : "Chicago"
},
{
"offset" : 42,
"value" : "IL"
},
{
"offset" : 46,
"value" : "United States"
}
],
"types" : [ "establishment" ]
}
],
"status" : "OK"
}
