HTTP/1.1 200 OK
Server: nginx
Date: Tue, 06 Dec 2016 17:08:05 GMT
Content-Type: application/json
Content-Length: 720
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS, DELETE
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 300
Cache-Control: no-cache, no-store
Request-Id: req_9hAlCj4xrKd75B
Stripe-Version: 2015-10-16
Strict-Transport-Security: max-age=31556926; includeSubDomains
Connection: Keep-alive

{
"id": "tok_9hAlYaVjGDtSmt",
"object": "token",
"card": {
"id": "card_9hAlxW89aNAbEl",
"object": "card",
"address_city": null,
"address_country": null,
"address_line1": null,
"address_line1_check": null,
"address_line2": null,
"address_state": null,
"address_zip": null,
"address_zip_check": null,
"brand": "Visa",
"country": "US",
"cvc_check": "unchecked",
"dynamic_last4": null,
"exp_month": 10,
"exp_year": 2020,
"funding": "credit",
"last4": "4242",
"metadata": {},
"name": null,
"tokenization_method": null
},
"client_ip": "96.95.111.1",
"created": 1481044085,
"livemode": false,
"type": "card",
"used": false
}
