use_frameworks!

platform :ios, '10.0'

target 'SpotHero_iOS_Partner_SDK_Example' do
  pod 'SpotHero_iOS_Partner_SDK', :path => '../'
  pod 'SwiftLint', '~>0.24.0'

  target 'SpotHero_iOS_Partner_SDK_Tests' do
    inherit! :search_paths
    pod 'VOKMockUrlProtocol', '~>2.4.0'
  end

  target 'SpotHero_iOS_Partner_SDK_ExampleUITests' do
    inherit! :search_paths
    pod 'VOKMockUrlProtocol', '~>2.4.0'
    pod 'KIF', '~>3.6.0'
  end
end

#Due to a bug in cocoapods 1.3.1
#https://discuss.circleci.com/t/xcode-9-build-failures-due-to-code-signing-errors-in-pods/16713
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
  end
end
