HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Tue, 06 Dec 2016 19:47:01 GMT
Expires: Tue, 06 Dec 2016 19:47:01 GMT
Cache-Control: private, max-age=300
Vary: Accept-Language
Content-Encoding: gzip
Server: pablo
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Alt-Svc: quic=":443"; ma=2592000; v="36,35,34"
Transfer-Encoding: chunked
Connection: Keep-alive

{
"predictions" : [
{
"description" : "Chicago, IL, United States",
"id" : "53eeb015d61056c54245a909c79862532fc953ad",
"matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"place_id" : "ChIJ7cv00DwsDogRAMDACa2m4K8",
"reference" : "CkQyAAAA_0W5aTAh9JsJMRYkHki9E6liUZJC0O4yVaTpHfTc8TOLotaERlCIZBIxaz5R0aGTByX9-bNkBpmNhqpzB0JmFhIQ2e3rBpffCcqxaVIbFFOHvRoUF9NnDhdKCoUkeQFnnmrXnxECU5U",
"structured_formatting" : {
"main_text" : "Chicago",
"main_text_matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"secondary_text" : "IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "Chicago"
},
{
"offset" : 9,
"value" : "IL"
},
{
"offset" : 13,
"value" : "United States"
}
],
"types" : [ "locality", "political", "geocode" ]
},
{
"description" : "Chinatown, Chicago, IL, United States",
"id" : "998b46a50620a8590b0c3489fbb6c09e16907def",
"matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"place_id" : "ChIJ8-LwlGAsDogRsQvm-wxiutY",
"reference" : "CkQ9AAAAoz8WGn3ZZAhQNEGhdLX2BVMWWnFse9mnaSE_QGasWoXV4DvEzeE9PKPXnEoHdLnSA7Ub1eIKF9ZCRrX_SV2ikRIQaGWTp2pDLxxzAo5F9GMZYBoUA1FW2H52qtnOrjRxVZn7NFBuANw",
"structured_formatting" : {
"main_text" : "Chinatown",
"main_text_matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"secondary_text" : "Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "Chinatown"
},
{
"offset" : 11,
"value" : "Chicago"
},
{
"offset" : 20,
"value" : "IL"
},
{
"offset" : 24,
"value" : "United States"
}
],
"types" : [ "neighborhood", "political", "geocode" ]
},
{
"description" : "Chicago Pizza and Oven Grinder Company, North Clark Street, Chicago, IL, United States",
"id" : "1f3990bcbcd6f97a3990c9d16ebb0b67d7595496",
"matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"place_id" : "ChIJx11WoWzTD4gRr2-RP6xmsaY",
"reference" : "CnRlAAAAFCW4glV4c2p-9jnHEsoZdE8bzdLy1tgNJuz7KyvCSI3vW6GVUK-40QOoYrNdCZGTjmtlQ-yYTCGPbtRfDwdVsoyWRFf2W57tE6FseYdpR-p8l5cwauJgCgbAhQD0h3j5ThrbQ3EBW9k3aetX_8SxihIQ7JCKOVML6Ax4Hfy88GGrZRoUdTCkoM6jdmhXB7HrjIPmHeiQorU",
"structured_formatting" : {
"main_text" : "Chicago Pizza and Oven Grinder Company",
"main_text_matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"secondary_text" : "North Clark Street, Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "Chicago Pizza and Oven Grinder Company"
},
{
"offset" : 40,
"value" : "North Clark Street"
},
{
"offset" : 60,
"value" : "Chicago"
},
{
"offset" : 69,
"value" : "IL"
},
{
"offset" : 73,
"value" : "United States"
}
],
"types" : [ "establishment" ]
},
{
"description" : "Chicago Athletic Association, South Michigan Avenue, Chicago, IL, United States",
"id" : "18d818016335180fee47f56ffeec57e8a7b090a1",
"matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"place_id" : "ChIJ3aVOQKQsDogRKqUuPtxhyRc",
"reference" : "CmRdAAAA7qmOsK9rHzLaDjX45WeJcMu923U8eHmeLhdZ0s3byuV9BxWP9IGbT-lOObzw3l2W7_7xmYwAg47ZxsR9rzRgU2cb28ROa7ZwcJjgTNk2FViz0mf9cQIWZvSSI4OablgSEhAr8xT8p4iBS2wHsSqgjut3GhSJx40gvbao9yR--rZVLk1SssBkew",
"structured_formatting" : {
"main_text" : "Chicago Athletic Association",
"main_text_matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"secondary_text" : "South Michigan Avenue, Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "Chicago Athletic Association"
},
{
"offset" : 30,
"value" : "South Michigan Avenue"
},
{
"offset" : 53,
"value" : "Chicago"
},
{
"offset" : 62,
"value" : "IL"
},
{
"offset" : 66,
"value" : "United States"
}
],
"types" : [ "establishment" ]
},
{
"description" : "Chicago Loop, Chicago, IL, United States",
"id" : "a2f3087af730df7130474d65b5aaa3a724efea49",
"matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"place_id" : "ChIJyUzrbr8sDogR_83q5x-GxzU",
"reference" : "CkRAAAAAH_3K9LgkfVoNg7KkfY6Y_RK518lv5CIvO1uxaZnbuS7qwOoRa6c_GwXQwgWsxSyF6LgFRa4f1r-VIG-Fd1mq6RIQZkXCFliykbiduUdbP0TS0xoUxvgLDAdH0hvmi7cvnDHHzF5oaPM",
"structured_formatting" : {
"main_text" : "Chicago Loop",
"main_text_matched_substrings" : [
{
"length" : 2,
"offset" : 0
}
],
"secondary_text" : "Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "Chicago Loop"
},
{
"offset" : 14,
"value" : "Chicago"
},
{
"offset" : 23,
"value" : "IL"
},
{
"offset" : 27,
"value" : "United States"
}
],
"types" : [ "neighborhood", "political", "geocode" ]
}
],
"status" : "OK"
}
