HTTP/1.1 200 OK
Server: nginx/1.11.0
Date: Mon, 01 Aug 2016 16:19:06 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: User-Agent, Cookie
X-Frame-Options: SAMEORIGIN
Allow: GET, HEAD, OPTIONS

{
"notifications": [],
"meta": {
"count": 17,
},
"data": {
"results": [{
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1390,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 15,
"price": 1500,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/320-w-erie-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"valet": {
"name": "Valet",
"slug": "valet",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/valet_ydnnm5.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 9183
}],
"facility": {
"id": 1477,
"parking_spot_id": 1477,
"title": "320 W Erie St. - Valet",
"description": "<p><strong>&nbsp;</strong></p><p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "320-w-erie-st",
"street_address": "320 West Erie Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.894011708375274,
"longitude": -87.63697385787964,
"company_id": 124,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "If you park past 8:00 pm, please confirm key pick up location with the valet before you leave your car. You will either need to pick your keys up from the valet or on-site at Hub 51."],
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"getting_here": "Enter this location at 320 W Erie. This Alfa Parking facility is located at the corner of Erie & Orleans.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.636573,
"state": "IL",
"types": ["physical", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.894204,
"id": 1392,
"street_address": "320 West Erie Street"
}, {
"city": "",
"zipcode": "",
"longitude": -87.63697385787964,
"state": "",
"types": ["search"],
"latitude": 41.894011708375274,
"id": 3693,
"street_address": ""
}],
"parking_type": "valet",
"redemption_instructions": [{
"illustration_id": "rc6uuzecbw3nfth0hlky",
"illustration_version": "1408636043",
"text": "Show the valet your SpotHero Parking Pass, either printed or on a mobile device.",
"id": 2522,
"position": 1
}, {
"illustration_id": "qxzzfxbzzpv9uttohajw",
"illustration_version": "1408636496",
"text": "The valet will hand you a ticket and will park your car. You must have this ticket in order to exit.",
"id": 2523,
"position": 2
}, {
"illustration_id": "jxvqbxtqj6tvdvdv0ytj",
"illustration_version": "1408636831",
"text": "When you're ready to go, show the valet your ticket and your car will be retrieved.",
"id": 2524,
"position": 3
}],
"mobile_enabled": true,
"parking_pass_type": "license_plate",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/320-w-erie-st",
"license_plate_required": true,
"wd_latitude": 41.894204,
"timezone": "America/Chicago",
"parking_spot_id": 1477,
"lowest_monthly_price": 0,
"distance": 60,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2814,y_1876/v1452723704/oh8saymqcpnjr8tll9h5.jpg",
"wd_longitude": -87.636573,
"title": "320 W Erie St. - Valet",
"longitude": -87.63697385787964,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.894011708375274,
"highest_price": 1500,
"lowest_price": 1500,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 282,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 19,
"price": 1900,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/310-w-huron?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"in-out": {
"name": "In and Out Allowed",
"slug": "in-out",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/in-out_ccmaiu.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 9694
}],
"facility": {
"id": 346,
"parking_spot_id": 346,
"title": "310 W Huron St. - Lot",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "310-w-huron",
"street_address": "310 W Huron St.",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.895025966184356,
"longitude": -87.6369309425354,
"company_id": 59,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["This location does not require a print out. Your vehicle is monitored by the license plate entered to SpotHero. "],
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"getting_here": "Enter this location at 310 W Huron St. This lot is operated by ABM Parking. It is located on the north/right-hand side of W Huron St. (a one-way street) between N Franklin St. and N Orleans St.\r\n\r\nYou can also access this facility at 705 N Orleans, on the east side of Orleans, just north of the intersection at Huron/Orleans.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.636222,
"state": "IL",
"types": ["physical", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.895015,
"id": 282,
"street_address": "310 W Huron St."
}, {
"city": "",
"zipcode": "",
"longitude": -87.6369309425354,
"state": "",
"types": ["search"],
"latitude": 41.895025966184356,
"id": 3692,
"street_address": ""
}],
"parking_type": "self",
"redemption_instructions": [{
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"text": "Make sure your license plate matches the plate on your Parking Pass. Failure to do so will result in a ticket or tow.",
"id": 25,
"position": 1
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "<p>You may park anywhere in the 310 W. Huron lot.</p>",
"id": 5998,
"position": 2
}, {
"illustration_id": "hodnezajkpxuiisu0i4e",
"illustration_version": "1408636065",
"text": "Simply leave when you're ready to go!",
"id": 27,
"position": 3
}],
"mobile_enabled": true,
"parking_pass_type": "license_plate",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [{
"message": "Ensure diane.baker@abm.com has admin access for all ABM Chicago locations (only Chicago!).",
"label": "Parking Point of Contact"
}, {
"message": "Chicago ABM's phone number (24/7): (312) 819-5050",
"label": "Additional Things You Should Know"
}],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/310-w-huron",
"license_plate_required": true,
"wd_latitude": 41.895015,
"timezone": "America/Chicago",
"parking_spot_id": 346,
"lowest_monthly_price": 0,
"distance": 62,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2880,y_1920/v1455124730/y1znnai1am3tv3gm91bq.jpg",
"wd_longitude": -87.636222,
"title": "310 W Huron St. - Lot",
"longitude": -87.6369309425354,
"phone_number_required": false,
"spot_notes": [{
"message": "A1 - (312) 829-3697; 2954 N California Ave, Chicago, IL 60618",
"label": "Additional Things You Should Know"
}, {
"message": "Please avoid parking anything larger than a sprinter van here. Lot is always busy and difficult to navigate, especially during commuter hours.",
"label": "Additional Things You Should Know"
}],
"latitude": 41.895025966184356,
"highest_price": 1900,
"lowest_price": 1900,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1248,
"unavailable": true,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 10,
"price": 1000,
"unavailable_reason": "outside operation hours",
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/301-w-huron-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
},
"valet": {
"name": "Valet",
"slug": "valet",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/valet_ydnnm5.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 8262
}],
"facility": {
"id": 1335,
"parking_spot_id": 1335,
"title": "301 W Huron St. - Valet/Self Park",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "301-w-huron-st",
"street_address": "301 West Huron Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.894363106605034,
"longitude": -87.63576149940491,
"company_id": 13,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "Depending on parking occupancy, you may be asked to leave your keys with the attendant.", "The valet at this facility leaves by 5pm every night. If you do not retrieve your vehicle by 5pm, your keys will be stored at the MidCity lot at 11 W. Elm St. (located about 1.3 miles northwest of this lot). Please call SpotHero customer assistance if you have any questions, ph#312-566-7768.", "No oversized vehicles allowed - no box trucks, trailers, vans, or buses."],
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"getting_here": "Enter this location at 301 W Huron. This is a MidCity Parking Facility on the South side of Huron. The closest intersection is Huron & Franklin.\r\n\r\n**Please take a moment and verify you are in the correct facility. There are two parking lots in the area, you must be parked in the MidCity lot on southwest corner of Franklin and Huron St. or you will be towed. There are green signs on the fence stating \"MidCity\", and there is a valet on-site (Mon-Fri, 8am - 5pm.) Please call SpotHero Customer Support with any questions, ph#312-566-7768.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.636076,
"state": "IL",
"types": ["physical", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.89454,
"id": 1248,
"street_address": "301 West Huron Street"
}, {
"city": "",
"zipcode": "",
"longitude": -87.63576149940491,
"state": "",
"types": ["search"],
"latitude": 41.894363106605034,
"id": 3691,
"street_address": ""
}],
"parking_type": "valet",
"redemption_instructions": [{
"illustration_id": "rc6uuzecbw3nfth0hlky",
"illustration_version": "1408636043",
"text": "<p>If you are parking during valet hours <strong>(7am - 5pm)</strong> Show the valet your SpotHero Parking Pass, either printed or on a mobile device. The valet will hand you a ticket and park your vehicle.</p>",
"id": 5626,
"position": 1
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "<p>If you are parking outside of valet hours <strong>(5:30pm - Midnight)</strong>, make sure your license plate matches the plate on your parking pass. You may park in any spot that does not say \"RESERVED\". Please be sure to leave before your reservation ends of you will be ticketed/towed.</p>",
"id": 5627,
"position": 2
}, {
"illustration_id": "jxvqbxtqj6tvdvdv0ytj",
"illustration_version": "1408636831",
"text": "When you're ready to go, show the valet your ticket and your car will be retrieved.",
"id": 4876,
"position": 3
}],
"mobile_enabled": true,
"parking_pass_type": "license_plate",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/301-w-huron-st",
"license_plate_required": true,
"wd_latitude": 41.89454,
"timezone": "America/Chicago",
"parking_spot_id": 1335,
"lowest_monthly_price": 0,
"distance": 76,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2880,y_1920/v1459197483/k2cnvtxn2frc5agfpplw.jpg",
"wd_longitude": -87.636076,
"title": "301 W Huron St. - Valet/Self Park",
"longitude": -87.63576149940491,
"phone_number_required": true,
"spot_notes": [{
"message": "A1 - (312) 829-3697; 2954 N California Ave, Chicago, IL 60618",
"label": "Additional Things You Should Know"
}],
"latitude": 41.894363106605034,
"highest_price": 1000,
"lowest_price": 1000,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1065,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 15,
"price": 1500,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/357-w-huron-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"valet": {
"name": "Valet",
"slug": "valet",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/valet_ydnnm5.svg"
},
"in-out": {
"name": "In and Out Allowed",
"slug": "in-out",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/in-out_ccmaiu.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 27987
}],
"facility": {
"status": "on_sales_allowed",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6379274577,
"state": "IL",
"street_address": "357 West Huron Street",
"latitude": 41.8946357941,
"id": 1065,
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"]
}],
"state": "IL",
"restrictions": ["Depending on parking occupancy, this facility may become a valet and you may be asked to leave your keys with the attendant."],
"redemption_instructions": [{
"position": 1,
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"id": 6855,
"text": "<p>Make sure your license plate matches the plate on your parking pass, and you are parked within your pre-selected reservation times. Failure to do so will result in a ticket or tow.</p>"
}, {
"position": 2,
"illustration_id": "rc6uuzecbw3nfth0hlky",
"illustration_version": "1408636043",
"id": 6856,
"text": "<p>When you arrive at the lot, please show your parking pass to the on-site attendant.<strong> If there is no attendant on-site,</strong> please park in any space that does not say \"Reserved\".&nbsp;</p>"
}, {
"position": 3,
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"id": 6857,
"text": "<p>Do not re-enter your license plate on site, we've got you covered!</p>"
}, {
"position": 4,
"illustration_id": "hodnezajkpxuiisu0i4e",
"illustration_version": "1408636065",
"id": 6858,
"text": "<p>Simply leave when you are ready to go!</p>"
}],
"zipcode": "60654",
"longitude": -87.6379274577,
"timezone": "America/Chicago",
"height_restriction": null,
"id": 1146,
"barcode_type": "qrcode",
"city": "Chicago",
"slug": "357-w-huron-st",
"online_commuter_rate_enter_start": null,
"title": "357 W Huron St. - Lot",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"company_id": 20,
"parking_spot_id": 1146,
"getting_here": "Enter this location at 357 W Huron. This lot is operated by Metro Valet. It is located on the South side of Huron St. between Orleans St. and Sedgwick St., just past the Green Door Tavern.",
"mobile_enabled": true,
"post_purchase_instructions": "",
"parking_pass_type": "license_plate",
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"latitude": 41.8946357941,
"parking_type": "valet",
"online_commuter_rate_enter_end": null,
"display_price_on_receipt": true,
"street_address": "357 West Huron Street",
"height_restriction_description": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/357-w-huron-st",
"license_plate_required": true,
"wd_latitude": 41.8946357941,
"timezone": "America/Chicago",
"parking_spot_id": 1146,
"lowest_monthly_price": 0,
"distance": 106,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2304,y_1536/v1422564582/fm60apbpaqbb1iivk7cy.jpg",
"wd_longitude": -87.6379274577,
"title": "357 W Huron St. - Lot",
"longitude": -87.6379274577,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.8946357941,
"highest_price": 1500,
"lowest_price": 1500,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 2997,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 10,
"price": 1000,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/673-n-franklin-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"covered-parking": {
"name": "Covered",
"slug": "covered-parking",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/covered-parking_pghvr4.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 30270
}],
"facility": {
"id": 3126,
"parking_spot_id": 3126,
"title": "673 N Franklin St. - Flair Tower Garage",
"description": "<p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "673-n-franklin-st",
"street_address": "673 North Franklin Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.894219353,
"longitude": -87.6352357864,
"company_id": 62,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": 84,
"height_restriction_description": "Height Restriction: 7'",
"barcode_type": "code128",
"post_purchase_instructions": "",
"restrictions": ["Height Restriction: 7'", "This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "Pedestrian access is available on the north side of Erie St., between Franklin and LaSale, just before you reach the alley. There will be a sign above the entrance reading \"Parking\"", "For all reservation changes, please allow 15 minutes for updates to take effect."],
"hours_of_operation": {
"text": [],
"periods": []
},
"getting_here": "Enter this location at 673 N Franklin St. This is the entrance address for the Flair Tower garage, operated by InterPark. It is located on the east side of N Franklin St. between Erie St. and Huron St. The entrance is located in the alley just south of The Franklin Room. This garage is also referred to as the \"222 W. Erie St.\" garage.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6356345,
"state": "IL",
"types": ["physical", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8943725,
"id": 3480,
"street_address": "673 North Franklin Street"
}, {
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6352357864,
"state": "IL",
"types": ["search", "vehicle-entrance"],
"latitude": 41.894219353,
"id": 3481,
"street_address": "673 North Franklin Street"
}],
"parking_type": "self",
"redemption_instructions": [{
"illustration_id": "egujzas3s3lavcix5mit",
"illustration_version": "1408636215",
"text": "<p>Scan your Bar Code at the red box attached to the entrance gate labelled \"SCAN BARCODE HERE.\" Hold the Bar Code face up, about 2 inches underneath the reader and the gate will open.</p>",
"id": 5362,
"position": 1
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "You may park anywhere that doesn't say \"Reserved\".",
"id": 4914,
"position": 2
}, {
"illustration_id": "egujzas3s3lavcix5mit",
"illustration_version": "1408636215",
"text": "<p>When exiting, scan your Bar Code at the red box attached to the exit gate labelled \"SCAN BARCODE HERE.\" Hold the Bar Code face up, about 2 inches underneath the reader and the gate will open.</p>",
"id": 5363,
"position": 3
}, {
"illustration_id": "yaemlosarlqngsj63tch",
"illustration_version": "1408636305",
"text": "The gate will open and you're free to go!",
"id": 4917,
"position": 4
}],
"mobile_enabled": true,
"parking_pass_type": "customer_scan",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/673-n-franklin-st",
"license_plate_required": false,
"wd_latitude": 41.8943725,
"timezone": "America/Chicago",
"parking_spot_id": 3126,
"lowest_monthly_price": 0,
"distance": 122,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_1025,y_683/v1459275353/edgw9zf4d0a41nuyd5sx.jpg",
"wd_longitude": -87.6356345,
"title": "673 N Franklin St. - Flair Tower Garage",
"longitude": -87.6352357864,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.894219353,
"highest_price": 1000,
"lowest_price": 1000,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1247,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 11,
"price": 1100,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/305-w-ontario-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 8258
}],
"facility": {
"status": "on_sales_allowed",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6358148,
"state": "IL",
"street_address": "305 West Ontario Street",
"latitude": 41.89315,
"id": 1247,
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"]
}],
"state": "IL",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "No oversized vehicles allowed - no box trucks, trailers, vans, or buses."],
"redemption_instructions": [{
"position": 1,
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"id": 6855,
"text": "<p>Make sure your license plate matches the plate on your parking pass, and you are parked within your pre-selected reservation times. Failure to do so will result in a ticket or tow.</p>"
}, {
"position": 2,
"illustration_id": "rc6uuzecbw3nfth0hlky",
"illustration_version": "1408636043",
"id": 6856,
"text": "<p>When you arrive at the lot, please show your parking pass to the on-site attendant.<strong> If there is no attendant on-site,</strong> please park in any space that does not say \"Reserved\".&nbsp;</p>"
}, {
"position": 3,
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"id": 6857,
"text": "<p>Do not re-enter your license plate on site, we've got you covered!</p>"
}, {
"position": 4,
"illustration_id": "hodnezajkpxuiisu0i4e",
"illustration_version": "1408636065",
"id": 6858,
"text": "<p>Simply leave when you are ready to go!</p>"
}],
"zipcode": "60654",
"longitude": -87.6358148,
"timezone": "America/Chicago",
"height_restriction": null,
"id": 1334,
"barcode_type": "qrcode",
"city": "Chicago",
"slug": "305-w-ontario-st",
"online_commuter_rate_enter_start": null,
"title": "305 W Ontario St. - Lot",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"company_id": 13,
"parking_spot_id": 1334,
"getting_here": "Enter this location at 305 W Ontario. This is a MidCity Parking Facility on the South side of Ontario. The closest intersection is Ontario & Franklin.",
"mobile_enabled": true,
"post_purchase_instructions": "",
"parking_pass_type": "license_plate",
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"latitude": 41.89315,
"parking_type": "self",
"online_commuter_rate_enter_end": null,
"display_price_on_receipt": true,
"street_address": "305 West Ontario Street",
"height_restriction_description": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/305-w-ontario-st",
"license_plate_required": true,
"wd_latitude": 41.89315,
"timezone": "America/Chicago",
"parking_spot_id": 1334,
"lowest_monthly_price": 0,
"distance": 165,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2304,y_1536/v1412525955/novsdopmcybqxaadmdsm.jpg",
"wd_longitude": -87.6358148,
"title": "305 W Ontario St. - Lot",
"longitude": -87.6358148,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.89315,
"highest_price": 1100,
"lowest_price": 1100,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1910,
"unavailable": true,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 18,
"price": 1800,
"unavailable_reason": "outside operation hours",
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/159-w-erie-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"valet": {
"name": "Valet",
"slug": "valet",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/valet_ydnnm5.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 12524
}],
"facility": {
"id": 1997,
"parking_spot_id": 1997,
"title": "159 W Erie St. - Valet",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "159-w-erie-st",
"street_address": "159 West Erie Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.893786,
"longitude": -87.6334978,
"company_id": 89,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once."],
"hours_of_operation": {
"text": [],
"periods": [{
"start_dow_int": 0,
"start_dow": "Mon",
"start_time": "17:00:00",
"hours_type": "open",
"end_dow": "Sun",
"end_dow_int": 6,
"end_time": "22:00:00"
}]
},
"getting_here": "Enter this location at 159 W Erie St. This is the Wildfire valet operated by Diamond Parking. It is located on the south side of W Erie St. between N Wells St. and N LaSalle Dr.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6334978,
"state": "IL",
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.893786,
"id": 2011,
"street_address": "159 West Erie Street"
}],
"parking_type": "valet",
"redemption_instructions": [{
"illustration_id": "rc6uuzecbw3nfth0hlky",
"illustration_version": "1408636043",
"text": "Show the valet your SpotHero Parking Pass, either printed or on a mobile device.",
"id": 745,
"position": 1
}, {
"illustration_id": "qxzzfxbzzpv9uttohajw",
"illustration_version": "1408636496",
"text": "The valet will hand you a ticket and will park your car. You must have this ticket in order to exit.",
"id": 746,
"position": 2
}, {
"illustration_id": "jxvqbxtqj6tvdvdv0ytj",
"illustration_version": "1408636831",
"text": "When you're ready to go, show the valet your ticket and your car will be retrieved.",
"id": 747,
"position": 3
}],
"mobile_enabled": true,
"parking_pass_type": "display",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/159-w-erie-st",
"license_plate_required": true,
"wd_latitude": 41.893786,
"timezone": "America/Chicago",
"parking_spot_id": 1997,
"lowest_monthly_price": 0,
"distance": 274,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2898,y_1932/v1451513116/h6p1a0cqpbc6sjbtallo.jpg",
"wd_longitude": -87.6334978,
"title": "159 W Erie St. - Valet",
"longitude": -87.6334978,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.893786,
"highest_price": 1800,
"lowest_price": 1800,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 230,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 8,
"price": 800,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/405-w-chicago-ave?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 5448
}],
"facility": {
"status": "on_sales_allowed",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6388573,
"state": "IL",
"street_address": "405 W. Chicago Ave.",
"latitude": 41.8965094,
"id": 230,
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"]
}],
"state": "IL",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "This location does not require a print out. Your vehicle is monitored by the license plate entered to SpotHero."],
"redemption_instructions": [{
"position": 1,
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"id": 25,
"text": "Make sure your license plate matches the plate on your Parking Pass. Failure to do so will result in a ticket or tow."
}, {
"position": 2,
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"id": 26,
"text": "You may park anywhere that doesn't say \"Reserved\"."
}, {
"position": 3,
"illustration_id": "hodnezajkpxuiisu0i4e",
"illustration_version": "1408636065",
"id": 27,
"text": "Simply leave when you're ready to go!"
}],
"zipcode": "60654",
"longitude": -87.6388573,
"timezone": "America/Chicago",
"height_restriction": null,
"id": 289,
"barcode_type": "qrcode",
"city": "Chicago",
"slug": "405-w-chicago-ave",
"online_commuter_rate_enter_start": null,
"title": "405 W Chicago Ave. - Lot",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"company_id": 79,
"parking_spot_id": 289,
"getting_here": "Enter this location at 405 W Chicago Avenue. This is a SP+ (formerly Central Parking) facility on the South side of Chicago. The closest intersection is Chicago and Sedgwick. Look for the yellow and black \"CPS Parking\" sign and the blue \"SpotHero\" sign.  .",
"mobile_enabled": true,
"post_purchase_instructions": "",
"parking_pass_type": "license_plate",
"hours_of_operation": {
"text": [],
"periods": []
},
"latitude": 41.8965094,
"parking_type": "self",
"online_commuter_rate_enter_end": null,
"display_price_on_receipt": true,
"street_address": "405 W. Chicago Ave.",
"height_restriction_description": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/405-w-chicago-ave",
"license_plate_required": true,
"wd_latitude": 41.8965094,
"timezone": "America/Chicago",
"parking_spot_id": 289,
"lowest_monthly_price": 0,
"distance": 287,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2144,y_1573/v1412346211/jzjvfx91aoopnwancric.jpg",
"wd_longitude": -87.6388573,
"title": "405 W Chicago Ave. - Lot",
"longitude": -87.6388573,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.8965094,
"highest_price": 800,
"lowest_price": 800,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1362,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 10,
"price": 1000,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/430-w-ohio-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"covered-parking": {
"name": "Covered",
"slug": "covered-parking",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/covered-parking_pghvr4.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 9005
}],
"facility": {
"id": 1449,
"parking_spot_id": 1449,
"title": "430 W Ohio St. - Lot",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "430-w-ohio-st",
"street_address": "430 West Ohio Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.89231858071554,
"longitude": -87.63938784599304,
"company_id": 13,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "No oversized vehicles allowed - no box trucks, trailers, vans, or buses.", "DO NOT park in the section labelled \"Private Parking,\" your vehicle will be towed. Please call SpotHero customer assistance at ph#312-566-7768 if you have any questions. "],
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"getting_here": "Enter this location at 430 W Ohio. This is a MidCity Parking Facility on the East side of Kingsbury. This is parking under the Ohio feeder ramp. No trucks, vans or oversized vehicles are permitted at this facility.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6400189833,
"state": "IL",
"types": ["physical", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8923008623,
"id": 1362,
"street_address": "430 West Ohio Street"
}, {
"city": "",
"zipcode": "",
"longitude": -87.63938784599304,
"state": "",
"types": ["search"],
"latitude": 41.89231858071554,
"id": 3696,
"street_address": ""
}],
"parking_type": "self",
"redemption_instructions": [{
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"text": "Make sure your license plate matches the plate on your Parking Pass. Failure to do so will result in a ticket or tow.",
"id": 170,
"position": 1
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "You may park anywhere that doesn't say \"Reserved\".",
"id": 171,
"position": 2
}, {
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"text": "Do not re-enter your license plate number onsite.  We've got you covered!",
"id": 172,
"position": 3
}, {
"illustration_id": "hodnezajkpxuiisu0i4e",
"illustration_version": "1408636065",
"text": "Simply leave when you're ready to go!",
"id": 173,
"position": 4
}],
"mobile_enabled": true,
"parking_pass_type": "license_plate",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/430-w-ohio-st",
"license_plate_required": true,
"wd_latitude": 41.8923008623,
"timezone": "America/Chicago",
"parking_spot_id": 1449,
"lowest_monthly_price": 0,
"distance": 331,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2880,y_1920/v1459198030/gixoto6wsrork5ff7cmr.jpg",
"wd_longitude": -87.6400189833,
"title": "430 W Ohio St. - Lot",
"longitude": -87.63938784599304,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.89231858071554,
"highest_price": 1000,
"lowest_price": 1000,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1227,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 15,
"price": 1500,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/681-n-lasalle-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"covered-parking": {
"name": "Covered",
"slug": "covered-parking",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/covered-parking_pghvr4.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 8098
}],
"facility": {
"id": 1314,
"parking_spot_id": 1314,
"title": "681 N LaSalle St. - Garage",
"description": "<p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "681-n-lasalle-st",
"street_address": "681 North LaSalle Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.8944375,
"longitude": -87.6325792,
"company_id": 7,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": 80,
"height_restriction_description": "Height Restriction: 6' 8\"",
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["Height Restriction: 6' 8\"", "This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "If the \"LOT FULL\" sign is on when you arrive, you will still have a spot in the garage. Scan your QR code at the entrance and continue into the garage. Please call SpotHero Customer Support with any questions, ph#312-566-7768"],
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"getting_here": "Enter this location at 681 N LaSalle. This is a self park garage for the Hotel Godfrey operated by LAZ Parking. In order to retrieve your car after your park, you need to enter through the hotel lobby and take the elevator to the parking garage. You may exit the building through the stairs, but this door is locked from the outside.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6325792,
"state": "IL",
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8944375,
"id": 1227,
"street_address": "681 North LaSalle Street"
}],
"parking_type": "self",
"redemption_instructions": [{
"illustration_id": "ggmmuyefup3xu8f6g13z",
"illustration_version": "1466114851",
"text": "<p>Scan your QR Code at the box with the red flashing lights. Hold the QR code about 2 inches away from the reader and the gate will open.</p>",
"id": 8159,
"position": 1
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "<p>You may park anywhere that doesn't say \"Reserved\".</p>",
"id": 8160,
"position": 2
}, {
"illustration_id": "ggmmuyefup3xu8f6g13z",
"illustration_version": "1466114851",
"text": "<p>When exiting, scan your QR Code again at the box with the red flashing lights.</p>",
"id": 8161,
"position": 3
}, {
"illustration_id": "yaemlosarlqngsj63tch",
"illustration_version": "1408636305",
"text": "<p>The gate will open and you're free to go!</p>",
"id": 8162,
"position": 4
}],
"mobile_enabled": true,
"parking_pass_type": "customer_scan",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/681-n-lasalle-st",
"license_plate_required": false,
"wd_latitude": 41.8944375,
"timezone": "America/Chicago",
"parking_spot_id": 1314,
"lowest_monthly_price": 0,
"distance": 338,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_1978,y_1923/v1412525152/widqreuixsabhey7uqwe.jpg",
"wd_longitude": -87.6325792,
"title": "681 N LaSalle St. - Garage",
"longitude": -87.6325792,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.8944375,
"highest_price": 1500,
"lowest_price": 1500,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1918,
"unavailable": true,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 17,
"price": 1700,
"unavailable_reason": "outside operation hours",
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/661-n-lasalle-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"valet": {
"name": "Valet",
"slug": "valet",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/valet_ydnnm5.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 12622
}],
"facility": {
"id": 2005,
"parking_spot_id": 2005,
"title": "661 N LaSalle St. - Valet",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "661-n-lasalle-st",
"street_address": "661 North LaSalle Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.8942403,
"longitude": -87.6325712,
"company_id": 89,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once."],
"hours_of_operation": {
"text": [],
"periods": [{
"start_dow_int": 0,
"start_dow": "Mon",
"start_time": "17:00:00",
"hours_type": "open",
"end_dow": "Sun",
"end_dow_int": 6,
"end_time": "22:00:00"
}]
},
"getting_here": "Enter this location at 661 N LaSalle St. This Fogo de Chao valet is operated by Diamond Parking. It is located on the east side of N LaSalle St. between W Erie St. and W Huron St. You may only access this valet traveling north on N LaSalle St.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6325712,
"state": "IL",
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8942403,
"id": 2019,
"street_address": "661 North LaSalle Street"
}],
"parking_type": "valet",
"redemption_instructions": [{
"illustration_id": "rc6uuzecbw3nfth0hlky",
"illustration_version": "1408636043",
"text": "Show the valet your SpotHero Parking Pass, either printed or on a mobile device.",
"id": 745,
"position": 1
}, {
"illustration_id": "qxzzfxbzzpv9uttohajw",
"illustration_version": "1408636496",
"text": "The valet will hand you a ticket and will park your car. You must have this ticket in order to exit.",
"id": 746,
"position": 2
}, {
"illustration_id": "jxvqbxtqj6tvdvdv0ytj",
"illustration_version": "1408636831",
"text": "When you're ready to go, show the valet your ticket and your car will be retrieved.",
"id": 747,
"position": 3
}],
"mobile_enabled": true,
"parking_pass_type": "display",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/661-n-lasalle-st",
"license_plate_required": true,
"wd_latitude": 41.8942403,
"timezone": "America/Chicago",
"parking_spot_id": 2005,
"lowest_monthly_price": 0,
"distance": 340,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_748,y_432/v1416947353/uqaptd64omhiyii8xpa2.png",
"wd_longitude": -87.6325712,
"title": "661 N LaSalle St. - Valet",
"longitude": -87.6325712,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.8942403,
"highest_price": 1700,
"lowest_price": 1700,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 740,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 22,
"price": 2200,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/641-n-lasalle-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 7895
}],
"facility": {
"status": "on_sales_allowed",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.632556,
"state": "IL",
"street_address": "641 North LaSalle Street",
"latitude": 41.8935133,
"id": 740,
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"]
}],
"state": "IL",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "This location does not require a print out. Your vehicle is monitored by the license plate entered to SpotHero."],
"redemption_instructions": [{
"position": 1,
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"id": 170,
"text": "Make sure your license plate matches the plate on your Parking Pass. Failure to do so will result in a ticket or tow."
}, {
"position": 2,
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"id": 171,
"text": "You may park anywhere that doesn't say \"Reserved\"."
}, {
"position": 3,
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"id": 172,
"text": "Do not re-enter your license plate number onsite.  We've got you covered!"
}, {
"position": 4,
"illustration_id": "hodnezajkpxuiisu0i4e",
"illustration_version": "1408636065",
"id": 173,
"text": "Simply leave when you're ready to go!"
}],
"zipcode": "60654",
"longitude": -87.632556,
"timezone": "America/Chicago",
"height_restriction": null,
"id": 815,
"barcode_type": "qrcode",
"city": "Chicago",
"slug": "641-n-lasalle-st",
"online_commuter_rate_enter_start": null,
"title": "641 N LaSalle St. - Lot",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"company_id": 31,
"parking_spot_id": 815,
"getting_here": "Enter this location at 641 N LaSalle. This is a Capital Parking Facility on the corner of LaSalle and Erie. It is directly across from Fogo De Chao.",
"mobile_enabled": true,
"post_purchase_instructions": "",
"parking_pass_type": "license_plate",
"hours_of_operation": {
"text": [],
"periods": [{
"start_dow_int": 0,
"start_dow": "Mon",
"start_time": "17:00:00",
"hours_type": "open",
"end_dow": "Mon",
"end_dow_int": 0,
"end_time": "06:00:00"
}, {
"start_dow_int": 0,
"start_dow": "Mon",
"start_time": "00:00:00",
"hours_type": "open",
"end_dow": "Mon",
"end_dow_int": 0,
"end_time": "06:00:00"
}, {
"start_dow_int": 1,
"start_dow": "Tue",
"start_time": "17:00:00",
"hours_type": "open",
"end_dow": "Fri",
"end_dow_int": 4,
"end_time": "06:00:00"
}, {
"start_dow_int": 5,
"start_dow": "Sat",
"start_time": "00:00:00",
"hours_type": "open",
"end_dow": "Sun",
"end_dow_int": 6,
"end_time": "00:00:00"
}]
},
"latitude": 41.8935133,
"parking_type": "self",
"online_commuter_rate_enter_end": null,
"display_price_on_receipt": true,
"street_address": "641 North LaSalle Street",
"height_restriction_description": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/641-n-lasalle-st",
"license_plate_required": true,
"wd_latitude": 41.8935133,
"timezone": "America/Chicago",
"parking_spot_id": 815,
"lowest_monthly_price": 0,
"distance": 357,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2501,y_1481/v1412526929/n9rgyicsxoott23rlasb.jpg",
"wd_longitude": -87.632556,
"title": "641 N LaSalle St. - Lot",
"longitude": -87.632556,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.8935133,
"highest_price": 2200,
"lowest_price": 2200,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1917,
"unavailable": true,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 17,
"price": 1700,
"unavailable_reason": "outside operation hours",
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/737-n-lasalle-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"valet": {
"name": "Valet",
"slug": "valet",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/valet_ydnnm5.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 35070
}],
"facility": {
"id": 2004,
"parking_spot_id": 2004,
"title": "737 N LaSalle St. - Valet",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "737-n-lasalle-st",
"street_address": "737 North LaSalle Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.8960083,
"longitude": -87.6324537,
"company_id": 89,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once."],
"hours_of_operation": {
"text": [],
"periods": [{
"start_dow_int": 1,
"start_dow": "Tue",
"start_time": "11:00:00",
"hours_type": "open",
"end_dow": "Fri",
"end_dow_int": 4,
"end_time": "21:00:00"
}, {
"start_dow_int": 5,
"start_dow": "Sat",
"start_time": "11:00:00",
"hours_type": "open",
"end_dow": "Sat",
"end_dow_int": 5,
"end_time": "17:00:00"
}, {
"start_dow_int": 6,
"start_dow": "Sun",
"start_time": "11:00:00",
"hours_type": "open",
"end_dow": "Sun",
"end_dow_int": 6,
"end_time": "21:00:00"
}]
},
"getting_here": "Enter this location at 737 N LaSalle St. This Cafe Iberico valet is operated by Diamond Parking. It is located on the east side of N LaSalle St. between W Superior St. and W Chicago Ave. You may only access this valet traveling north on N LaSalle St.",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6324537,
"state": "IL",
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8960083,
"id": 2018,
"street_address": "737 North LaSalle Street"
}],
"parking_type": "valet",
"redemption_instructions": [{
"illustration_id": "rc6uuzecbw3nfth0hlky",
"illustration_version": "1408636043",
"text": "Show the valet your SpotHero Parking Pass, either printed or on a mobile device.",
"id": 745,
"position": 1
}, {
"illustration_id": "qxzzfxbzzpv9uttohajw",
"illustration_version": "1408636496",
"text": "The valet will hand you a ticket and will park your car. You must have this ticket in order to exit.",
"id": 746,
"position": 2
}, {
"illustration_id": "jxvqbxtqj6tvdvdv0ytj",
"illustration_version": "1408636831",
"text": "When you're ready to go, show the valet your ticket and your car will be retrieved.",
"id": 747,
"position": 3
}],
"mobile_enabled": true,
"parking_pass_type": "display",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/737-n-lasalle-st",
"license_plate_required": true,
"wd_latitude": 41.8960083,
"timezone": "America/Chicago",
"parking_spot_id": 2004,
"lowest_monthly_price": 0,
"distance": 386,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2880,y_1920/v1455139275/bpemxgtkekbx3zrxokgy.jpg",
"wd_longitude": -87.6324537,
"title": "737 N LaSalle St. - Valet",
"longitude": -87.6324537,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.8960083,
"highest_price": 1700,
"lowest_price": 1700,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 1271,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 12,
"price": 1200,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/505-n-orleans-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
},
"covered-parking": {
"name": "Covered",
"slug": "covered-parking",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/covered-parking_pghvr4.svg"
},
"attendant": {
"name": "On Site Staff",
"slug": "attendant",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/attendant_tur8dg.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 8332
}],
"facility": {
"id": 1358,
"parking_spot_id": 1358,
"title": "505 N Orleans St. - Garage",
"description": "<p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "505-n-orleans-st",
"street_address": "505 North Orleans Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.8908624,
"longitude": -87.6369753,
"company_id": 7,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": 80,
"height_restriction_description": "Height Restriction: 6' 8\"",
"barcode_type": "code128",
"post_purchase_instructions": "",
"restrictions": ["Height Restriction: 6' 8\"", "This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "Pedestrian entry is located at 320 W. Illinois St, through the River North Park Condominium lobby", "For all reservation changes, please allow 15 minutes for updates to take effect."],
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"getting_here": "Enter this location at 505 N Orleans. This is a LAZ Parking Facility on the East side of Orleans. The closest intersection is Orleans & Illinois. Look for the Blue, Red, & White \"Parking\" sign.  In order to get back into the garage, you may need to enter through the River North Park residential building (320 W Illinois St.) around the corner on Illinois St. ",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6369753,
"state": "IL",
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8908624,
"id": 1271,
"street_address": "505 North Orleans Street"
}],
"parking_type": "self",
"redemption_instructions": [{
"illustration_id": "fosxlhppgwqxkrs1ijbx",
"illustration_version": "1408636373",
"text": "Pull a ticket when you enter.",
"id": 261,
"position": 1
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "You may park anywhere that doesn't say \"Reserved\".",
"id": 23,
"position": 2
}, {
"illustration_id": "egujzas3s3lavcix5mit",
"illustration_version": "1408636215",
"text": "<p>When exiting, <strong>DO NOT USE THE SELF-PAY KIOSK.</strong> Drive to the exit gate,&nbsp;insert the ticket you pulled upon entry into the machine. Then scan your SpotHero barcode on your SpotHero confirmation using the blue scanner labelled \"Online Customers.\"</p>",
"id": 262,
"position": 3
}, {
"illustration_id": "yaemlosarlqngsj63tch",
"illustration_version": "1408636305",
"text": "The gate will open and you're free to go!",
"id": 107,
"position": 4
}],
"mobile_enabled": true,
"parking_pass_type": "customer_scan",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/505-n-orleans-st",
"license_plate_required": false,
"wd_latitude": 41.8908624,
"timezone": "America/Chicago",
"parking_spot_id": 1358,
"lowest_monthly_price": 0,
"distance": 405,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2880,y_1920/v1455230063/hlytppubmlprim9bqeiv.jpg",
"wd_longitude": -87.6369753,
"title": "505 N Orleans St. - Garage",
"longitude": -87.6369753,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.8908624,
"highest_price": 1200,
"lowest_price": 1200,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 327,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 9,
"price": 900,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/320-w-chestnut-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"in-out": {
"name": "In and Out Allowed",
"slug": "in-out",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/in-out_ccmaiu.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"wheelchair": {
"name": "Handicap Accessible",
"slug": "wheelchair",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/wheelchair_s08czs.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 8214
}],
"facility": {
"id": 394,
"parking_spot_id": 394,
"title": "320 W Chestnut St. - Under EL",
"description": "<p>This parking spot is&nbsp;under&nbsp;the&nbsp;EL&nbsp;tracks. You are getting a great price, but please note the following:</p><div><ul><li>Your parking spot is beneath an active train track.</li><li>Oil may drip from the tracks.</li><li>It can be dark, unpaved, &amp; impacted by the unpredictable Chicago weather.</li></ul></div><p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "320-w-chestnut-st",
"street_address": "320 West Chestnut Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60610",
"latitude": 41.8981725,
"longitude": -87.6366716,
"company_id": 79,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["This parking spot is under the EL tracks. You are getting a great price, but please remember, you are parking beneath an active train line. Oil may drip from the tracks. It can be dark, unpaved, & impacted by the unpredictable Chicago weather. SpotHero assumes no liability for any vehicle damages that may occur. Please park at your own risk.", "This location does not require a print out. Your vehicle is monitored by the license plate entered to SpotHero."],
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"getting_here": "Enter this location at 320 W Chestnut St. This is a Central Parking Facility located underneath the EL train tracks between W Chestnut St. and W Locust St. right off of N Orleans. St. Park anywhere between the SpotHero signs labeled \"320 W Chestnut\" and look for \"CPS\" and \"A1 Towing\" signs.",
"addresses": [{
"city": "Chicago",
"zipcode": "60610",
"longitude": -87.6366716,
"state": "IL",
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8981725,
"id": 327,
"street_address": "320 West Chestnut Street"
}],
"parking_type": "self",
"redemption_instructions": [{
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"text": "Make sure your license plate matches the plate on your Parking Pass. Failure to do so will result in a ticket or tow.",
"id": 36,
"position": 1
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "You may park anywhere between the SpotHero signs labeled \"320 W Chestnut\".",
"id": 37,
"position": 2
}, {
"illustration_id": "hodnezajkpxuiisu0i4e",
"illustration_version": "1408636065",
"text": "Simply leave when you're ready to go!",
"id": 27,
"position": 3
}],
"mobile_enabled": true,
"parking_pass_type": "license_plate",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/320-w-chestnut-st",
"license_plate_required": true,
"wd_latitude": 41.8981725,
"timezone": "America/Chicago",
"parking_spot_id": 394,
"lowest_monthly_price": 0,
"distance": 407,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_1554,y_1358/v1412288176/vtheizqsy0fdnlu4ibko.jpg",
"wd_longitude": -87.6366716,
"title": "320 W Chestnut St. - Under EL",
"longitude": -87.6366716,
"phone_number_required": true,
"spot_notes": [{
"message": "We have spots in 3 out of the 4 bays here. One of the bays is owned by the car wash in the area. There is a lot of construction in this area going (we're reaching out to make sure these vehicles are supposed to be here), but make sure customers are checking all of the bays first before assuming it is full.",
"label": "Additional Things You Should Know"
}, {
"message": "A1 Citywide tows here: (773) 539-2954",
"label": "Additional Things You Should Know"
}],
"latitude": 41.8981725,
"highest_price": 900,
"lowest_price": 900,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 4722,
"unavailable": true,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 8,
"price": 800,
"unavailable_reason": "outside operation hours",
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/860-n-orleans-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"in-out": {
"name": "In and Out Allowed",
"slug": "in-out",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/in-out_ccmaiu.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 48190
}],
"facility": {
"id": 4892,
"parking_spot_id": 4892,
"title": "860 N Orleans St. - Big and Little's - Lot",
"description": "<p><strong>Please Note:</strong></p><p>If you need to change or update your license plate number after purchasing, you can do so under \"My Reservations\" in your account.</p><p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "860-n-orleans-st",
"street_address": "860 North Orleans Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60610",
"latitude": 41.8983474,
"longitude": -87.6375545,
"company_id": 58,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": null,
"height_restriction_description": null,
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["SpotHero and local parking provider are not responsible for theft, damage to your vehicle, or personal property. Please keep vehicle locked and do not leave valuables in your car."],
"hours_of_operation": {
"text": [],
"periods": [{
"start_dow_int": 0,
"start_dow": "Mon",
"start_time": "22:00:00",
"hours_type": "open",
"end_dow": "Mon",
"end_dow_int": 0,
"end_time": "08:00:00"
}, {
"start_dow_int": 0,
"start_dow": "Mon",
"start_time": "00:00:00",
"hours_type": "open",
"end_dow": "Mon",
"end_dow_int": 0,
"end_time": "08:00:00"
}, {
"start_dow_int": 1,
"start_dow": "Tue",
"start_time": "22:00:00",
"hours_type": "open",
"end_dow": "Fri",
"end_dow_int": 4,
"end_time": "08:00:00"
}, {
"start_dow_int": 5,
"start_dow": "Sat",
"start_time": "22:00:00",
"hours_type": "open",
"end_dow": "Sat",
"end_dow_int": 5,
"end_time": "00:00:00"
}, {
"start_dow_int": 6,
"start_dow": "Sun",
"start_time": "00:00:00",
"hours_type": "open",
"end_dow": "Sun",
"end_dow_int": 6,
"end_time": "00:00:00"
}]
},
"getting_here": "Enter this location at 860 N Orleans St. This is the lot adjacent to Big and Little's restaurant. It is located on the west side of N Orleans St. between W Chestnut St. and W Locust St. The entrance to the lot is encircled by a black fence. Please park perpendicularly along the north side of the lot, opposite of the restaurant. See photos for reference. ",
"addresses": [{
"city": "Chicago",
"zipcode": "60610",
"longitude": -87.6375545,
"state": "IL",
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8983474,
"id": 5420,
"street_address": "860 North Orleans Street"
}],
"parking_type": "self",
"redemption_instructions": [{
"illustration_id": "pp3uajdxl5u9lrnak1as",
"illustration_version": "1408636881",
"text": "Make sure your license plate matches the plate on your Parking Pass. Failure to do so will result in a ticket or tow.",
"id": 8766,
"position": 1
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "<p>You must park on the north side of the lot perpendicular to the building across from the restaurant.</p>",
"id": 8793,
"position": 2
}, {
"illustration_id": "hodnezajkpxuiisu0i4e",
"illustration_version": "1408636065",
"text": "Simply leave when you're ready to go!",
"id": 8768,
"position": 3
}],
"mobile_enabled": true,
"parking_pass_type": "license_plate",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [{
"message": "Chicago Independent Sellers: there is a Chicago City Tax breakdown on the backend of all independent spots. The rate that are on the website will look different from the rate that is displayed on the backend. Customers should not have any questions about this, but if a hero does, please ask Haley or Michelle for clarification.",
"label": "Additional Things You Should Know"
}],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/860-n-orleans-st",
"license_plate_required": true,
"wd_latitude": 41.8983474,
"timezone": "America/Chicago",
"parking_spot_id": 4892,
"lowest_monthly_price": 0,
"distance": 433,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_910,y_675/v1468601646/gnz7f8zliud4ycpvh1ym.png",
"wd_longitude": -87.6375545,
"title": "860 N Orleans St. - Big and Little's - Lot",
"longitude": -87.6375545,
"phone_number_required": true,
"spot_notes": [],
"latitude": 41.8983474,
"highest_price": 800,
"lowest_price": 800,
"highest_monthly_price": 0
}, {
"hourly_rates": [{
"rule_type": "multirate",
"online_commuter_rate_enter_start": null,
"ends": "2016-10-14T00:16",
"rule_group_id": 2331,
"unavailable": false,
"rule_trail": null,
"title": "Default",
"event_id": null,
"display_price": 20,
"price": 2000,
"unavailable_reason": null,
"online_commuter_rate_description": null,
"online_commuter_rate": false,
"url": "https://pdp.kickthe.tires/chicago-parking/220-w-illinois-st?start_date=10-13-2016&start_time=0716PM&end_date=10-14-2016&end_time=1216AM",
"amenities": {
"mobile": {
"name": "Mobile Pass Accepted",
"slug": "mobile",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/mobile_aorjqp.svg"
},
"self-park": {
"name": "Self Park",
"slug": "self-park",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/self-park_q4ppzl.svg"
},
"covered-parking": {
"name": "Covered",
"slug": "covered-parking",
"visible": true,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/covered-parking_pghvr4.svg"
},
"paved": {
"name": "Paved",
"slug": "paved",
"visible": false,
"icon_url": "http://res.cloudinary.com/spothero/image/upload/v1471462941/amenity_icons/paved_u1xmia.svg"
}
},
"starts": "2016-10-13T19:16",
"duration": 5.0,
"online_commuter_rate_enter_end": null,
"rule_id": 17642
}],
"facility": {
"id": 2422,
"parking_spot_id": 2422,
"title": "220 W Illinois St. - Garage",
"description": "<p><strong>Questions?</strong></p><p>Shoot us an email at support@spothero.com or give us a call at (312) 566-7768. Our Customer Heroes are here to help!</p>",
"status": "on_sales_allowed",
"slug": "220-w-illinois-st",
"street_address": "220 West Illinois Street",
"city": "Chicago",
"state": "IL",
"zipcode": "60654",
"latitude": 41.8908382469,
"longitude": -87.6346155418,
"company_id": 79,
"timezone": "America/Chicago",
"display_price_on_receipt": true,
"height_restriction": 98,
"height_restriction_description": "Height Restriction: 8' 2\"",
"barcode_type": "qrcode",
"post_purchase_instructions": "",
"restrictions": ["Height Restriction: 8' 2\"", "This facility does NOT allow in/out privileges. You CANNOT enter & exit more than once.", "The scanner window sits low on the ticket dispenser upon entry. You may have to pull forward and open driver-side door to reach the scanner window. We apologize for any inconvenience may cause. If you cannot reach the scanner, pull a ticket and use the \"Assistance\" button while exiting.   ", "For all reservation changes, please allow 15 minutes for updates to take effect."],
"hours_of_operation": {
"text": ["This facility is open 24/7."],
"periods": []
},
"getting_here": "Enter this location at 220 W Illinois St. This garage is operated by SP+. It is located on the north side of W Illinois St. between N Franklin St. and N Wells St. The entrance to this garage is located in the alley north of Illinois St., just follow the blue \"P\" parking sign affixed to the building. \r\nYou can also access this facility from N. Franklin St. Take the alley on the east side Franklin St., between W. Grand and W. Illinois St. (directly behind Binny's Beverage Depot). Continue heading east down the alley, follow the posted signs, garage entrance will be on your right. ",
"addresses": [{
"city": "Chicago",
"zipcode": "60654",
"longitude": -87.6346155418,
"state": "IL",
"types": ["physical", "search", "walking-distance", "default-vehicle-entrance"],
"latitude": 41.8908382469,
"id": 2612,
"street_address": "220 West Illinois Street"
}],
"parking_type": "self",
"redemption_instructions": [{
"illustration_id": "egujzas3s3lavcix5mit",
"illustration_version": "1408636215",
"text": "<p>Scan your QR Code at the ticket dispenser. Scanner window is located mid-way on machine, about 6 inches below \"Push For Ticket\" sign. Hold the QR code about 2 inches away from the reader and the gate will open. *Scanner sits low on the dispenser, you may have to open driver-side door to reach the scanner*</p>",
"id": 2843,
"position": 1
}, {
"illustration_id": "fosxlhppgwqxkrs1ijbx",
"illustration_version": "1408636373",
"text": "<p><span style=\"color: #666666; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; line-height: 18.5714302062988px;\">You will be issued a ticket and the gate will open. You must have this ticket to exit.</span></p>",
"id": 1017,
"position": 2
}, {
"illustration_id": "b2omz3upgcpjn44cyhjb",
"illustration_version": "1408636122",
"text": "<p>Choose your spot! You may park in the numbered spaces.</p>",
"id": 6378,
"position": 3
}, {
"illustration_id": "fosxlhppgwqxkrs1ijbx",
"illustration_version": "1408636373",
"text": "<p><span style=\"color: #666666; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; line-height: 18.5714302062988px;\">Insert the ticket you received upon arrival.</span></p>",
"id": 1019,
"position": 4
}, {
"illustration_id": "yaemlosarlqngsj63tch",
"illustration_version": "1408636305",
"text": "<p><span style=\"color: #666666; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; line-height: 18.5714302062988px;\">The gate will open and you're free to go!</span></p>",
"id": 1020,
"position": 5
}],
"mobile_enabled": true,
"parking_pass_type": "customer_scan",
"online_commuter_rate": false,
"online_commuter_rate_description": "",
"online_commuter_rate_enter_start": null,
"online_commuter_rate_enter_end": null
},
"monthly_rates": [],
"operator_notes": [],
"spot_url": "https://pdp.kickthe.tires/chicago-parking/220-w-illinois-st",
"license_plate_required": false,
"wd_latitude": 41.8908382469,
"timezone": "America/Chicago",
"parking_spot_id": 2422,
"lowest_monthly_price": 0,
"distance": 440,
"default_image_url": "https://res.cloudinary.com/spothero/image/upload/c_fill,f_auto,g_xy_center,h_98,q_50,w_145,x_2607,y_1427/v1427498156/oao8buevkeiouqmsj46f.jpg",
"wd_longitude": -87.6346155418,
"title": "220 W Illinois St. - Garage",
"longitude": -87.6346155418,
"phone_number_required": false,
"spot_notes": [],
"latitude": 41.8908382469,
"highest_price": 2000,
"lowest_price": 2000,
"highest_monthly_price": 0
}]
}
}
