HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Wed, 14 Dec 2016 22:16:40 GMT
Expires: Wed, 14 Dec 2016 22:16:40 GMT
Cache-Control: private, max-age=300
Vary: Accept-Language
Content-Encoding: gzip
Server: pablo
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Alt-Svc: quic=":443"; ma=2592000; v="35,34"
Transfer-Encoding: chunked
Connection: Keep-alive

{
"predictions" : [
{
"description" : "100 West Monroe Street, Chicago, IL, United States",
"id" : "df709dbcb561373903013f0aada65a2fbd320da7",
"matched_substrings" : [
{
"length" : 3,
"offset" : 0
},
{
"length" : 11,
"offset" : 4
}
],
"place_id" : "ChIJlfSxg7ssDogRUnH9yV3Oiow",
"reference" : "ClRKAAAA9mOFwp-56-gcbFcl3aGZ4DJx82SXyumkIedVk1yGJarl_kt9hHYniaVyBtKxJmX7G9Vs8THbpGY3diZJv2dE3_C7_laLm-5qnjFfeSGTLgkSEGw2AMU3YhNQ-46A7ocUBIoaFEWalYdgHCV2QW96-zklCaYu2hoe",
"structured_formatting" : {
"main_text" : "100 West Monroe Street",
"main_text_matched_substrings" : [
{
"length" : 3,
"offset" : 0
},
{
"length" : 11,
"offset" : 4
}
],
"secondary_text" : "Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "100"
},
{
"offset" : 4,
"value" : "West Monroe Street"
},
{
"offset" : 24,
"value" : "Chicago"
},
{
"offset" : 33,
"value" : "IL"
},
{
"offset" : 37,
"value" : "United States"
}
],
"types" : [ "street_address", "geocode" ]
},
{
"description" : "100 West Monroe Partnership, West Monroe Street, Chicago, IL, United States",
"id" : "f0d566d386ceb135cfdd9cefa8bf3e748a7f5937",
"matched_substrings" : [
{
"length" : 15,
"offset" : 0
}
],
"place_id" : "ChIJ8fEtgrssDogR3_8YSnZjezQ",
"reference" : "CmRZAAAAYJ7ueM5sQBqlFtRafawhrzCe9r9eAWHzqFbhiA--2lojlIMwMDR8ssCXI8QqkGo9pgO4OabC75YxopY604iTblC9BrhedKc_mdN2HLlXWHWHSJOn5c3Qi2p9XzqbVMqDEhBG5HoytBolSutY8pcw6gmjGhRAdPKb_FgU8s4mUNFuICmlk8yT4g",
"structured_formatting" : {
"main_text" : "100 West Monroe Partnership",
"main_text_matched_substrings" : [
{
"length" : 15,
"offset" : 0
}
],
"secondary_text" : "West Monroe Street, Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "100 West Monroe Partnership"
},
{
"offset" : 29,
"value" : "West Monroe Street"
},
{
"offset" : 49,
"value" : "Chicago"
},
{
"offset" : 58,
"value" : "IL"
},
{
"offset" : 62,
"value" : "United States"
}
],
"types" : [ "establishment" ]
},
{
"description" : "100 West Monroe Street, Niles, IL, United States",
"id" : "9308d0ebfd10283c8ff7d4b83648ca0ad4f830af",
"matched_substrings" : [
{
"length" : 15,
"offset" : 0
}
],
"place_id" : "EjAxMDAgV2VzdCBNb25yb2UgU3RyZWV0LCBOaWxlcywgSUwsIFVuaXRlZCBTdGF0ZXM",
"reference" : "CkQ0AAAATddcqLj2CbMzYEByJF_i9JFhz0MbxHRUS1NqLcODE-_EoOQP6JjObYfOvoJN4wgXejYlRaerCufm2Gec6JdbVxIQEhbFlVnnP3HY7BcwVCQAqRoUO4f_bA6DfM35_kh1UnOironHUBM",
"structured_formatting" : {
"main_text" : "100 West Monroe Street",
"main_text_matched_substrings" : [
{
"length" : 15,
"offset" : 0
}
],
"secondary_text" : "Niles, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "100 West Monroe Street"
},
{
"offset" : 24,
"value" : "Niles"
},
{
"offset" : 31,
"value" : "IL"
},
{
"offset" : 35,
"value" : "United States"
}
],
"types" : [ "route", "geocode" ]
},
{
"description" : "100 West Monroe Street, Villa Park, IL, United States",
"id" : "87470ffd8885f0ce717f43668d8d7df3449de2f6",
"matched_substrings" : [
{
"length" : 15,
"offset" : 0
}
],
"place_id" : "EjUxMDAgV2VzdCBNb25yb2UgU3RyZWV0LCBWaWxsYSBQYXJrLCBJTCwgVW5pdGVkIFN0YXRlcw",
"reference" : "CkQ5AAAAlDWFfUZW1ZGT2M8NTKSc03PEY-nTlXe81lvUKvRUy5rUnYyWabNYV_NmLQSeBsHN6uu1fAmBT0o_fK08Di2ABRIQYcFDB1FkvcKkrG-lH8tm6hoUfOaOBGJqjBWPj69AJJfIDnm60nc",
"structured_formatting" : {
"main_text" : "100 West Monroe Street",
"main_text_matched_substrings" : [
{
"length" : 15,
"offset" : 0
}
],
"secondary_text" : "Villa Park, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "100 West Monroe Street"
},
{
"offset" : 24,
"value" : "Villa Park"
},
{
"offset" : 36,
"value" : "IL"
},
{
"offset" : 40,
"value" : "United States"
}
],
"types" : [ "route", "geocode" ]
},
{
"description" : "100 E Monroe St, Chicago, IL, United States",
"id" : "122d44dcc10987e06f1229fbc9c60652b9e8d9c8",
"matched_substrings" : [
{
"length" : 15,
"offset" : 0
}
],
"place_id" : "EisxMDAgRSBNb25yb2UgU3QsIENoaWNhZ28sIElMLCBVbml0ZWQgU3RhdGVz",
"reference" : "CjQvAAAAIM-PoG02cZyJslZL-LHPXElhbImoLvtpyvEHBPdG4kk-ZJo5fSGU0UMC8Jt9oJECEhDKGKqkPtXoTPMdAMq2yZizGhT4BbbArepjq-CdoWidoquNlQ_4wg",
"structured_formatting" : {
"main_text" : "100 E Monroe St",
"main_text_matched_substrings" : [
{
"length" : 15,
"offset" : 0
}
],
"secondary_text" : "Chicago, IL, United States"
},
"terms" : [
{
"offset" : 0,
"value" : "100 E Monroe St"
},
{
"offset" : 17,
"value" : "Chicago"
},
{
"offset" : 26,
"value" : "IL"
},
{
"offset" : 30,
"value" : "United States"
}
],
"types" : [ "route", "geocode" ]
}
],
"status" : "OK"
}
