HTTP/1.1 201 CREATED
Server: nginx/1.11.0
Date: Tue, 02 Aug 2016 19:01:55 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: User-Agent, Cookie
X-Frame-Options: SAMEORIGIN
Allow: POST, OPTIONS


{
"notifications": [],
	"meta": {},
	"data": {
		"display_id": 3559198,
		"cancel_url": "http://api.pdp.kickthe.tires/partner/v1/reservations/3559198/cancel/?key=bdce43f47b539e06e0cce19ffff2fa2f37e5b0d391caf2a76b5e9afbd34a9292",
		"ends": "2016-08-02T05:08:00Z",
		"rental_id": 3559198,
		"reservation_status": "valid",
		"starts": "2016-08-02T00:08:00Z",
		"price": 1500,
		"reservation_url": "http://api.pdp.kickthe.tires/partner/v1/reservations/3559198/?key=bdce43f47b539e06e0cce19ffff2fa2f37e5b0d391caf2a76b5e9afbd34a9292",
		"license_plate": "",
		"barcode_content": "3559198",
		"facility_id": 1477,
		"facility_title": "320 W Erie St. - Valet"
	}
}
