# Make Swift-only frameworks usable.
use_frameworks!

target 'SpotHero_Google_Places_Wrapper_Example' do
    pod 'SpotHero_iOS_Google_Places_Wrapper', :path => '../'
end

target 'SpotHero_Google_Places_Wrapper_ExampleTests' do
    pod 'SpotHero_iOS_Google_Places_Wrapper', :path => '../'
end
